DEBUG 2018-10-19 11:34:28,867: 	 Executing command: 'submit'
DEBUG 2018-10-19 11:34:28,868: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2018-10-19 11:34:28,927: 	 Checking credentials
DEBUG 2018-10-19 11:34:28,927: 	 Found proxy file /tmp/x509up_u107749
DEBUG 2018-10-19 11:34:28,927: 	 Getting proxy life time left
DEBUG 2018-10-19 11:34:30,232: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -timeleft
 output : 604291

 error: 
 retcode : 0
DEBUG 2018-10-19 11:34:30,840: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -actimeleft
 output : 604291

 error: 
 retcode : 0
DEBUG 2018-10-19 11:34:30,841: 	 Proxy valid for 167:51:31 hours
INFO 2018-10-19 11:34:30,841: 	 Will use CRAB configuration file CreateCrabConfigFilesData.py
DEBUG 2018-10-19 11:34:30,841: 	 Loading CRAB configuration file.
ERROR 2018-10-19 11:34:30,902: 	 Error while loading CRAB configuration:
Unable to find a Configuration object instance in file:
/afs/cern.ch/user/g/gbakas/CRAB3-jobs/CMSSW_9_4_2/src/UserCode/TopAnalysis/prod/ttbar/CreateCrabConfigFilesData.py

Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2018-10-19 11:34:30,902: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 303, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 84, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
Unable to find a Configuration object instance in file:
/afs/cern.ch/user/g/gbakas/CRAB3-jobs/CMSSW_9_4_2/src/UserCode/TopAnalysis/prod/ttbar/CreateCrabConfigFilesData.py

Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2018-10-19 11:48:38,254: 	 Executing command: 'submit'
DEBUG 2018-10-19 11:48:38,258: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2018-10-19 11:48:38,268: 	 Checking credentials
DEBUG 2018-10-19 11:48:38,271: 	 Found proxy file /tmp/x509up_u107749
DEBUG 2018-10-19 11:48:38,271: 	 Getting proxy life time left
DEBUG 2018-10-19 11:48:38,976: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -timeleft
 output : 603443

 error: 
 retcode : 0
DEBUG 2018-10-19 11:48:39,683: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -actimeleft
 output : 603442

 error: 
 retcode : 0
DEBUG 2018-10-19 11:48:39,683: 	 Proxy valid for 167:37:23 hours
INFO 2018-10-19 11:48:39,684: 	 Will use CRAB configuration file CreateCrabConfigFilesData.py
DEBUG 2018-10-19 11:48:39,685: 	 Loading CRAB configuration file.
ERROR 2018-10-19 11:48:39,773: 	 Error while loading CRAB configuration:
Unable to find a Configuration object instance in file:
/afs/cern.ch/user/g/gbakas/CRAB3-jobs/CMSSW_9_4_2/src/UserCode/TopAnalysis/prod/ttbar/CreateCrabConfigFilesData.py

Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2018-10-19 11:48:39,773: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 303, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 84, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
Unable to find a Configuration object instance in file:
/afs/cern.ch/user/g/gbakas/CRAB3-jobs/CMSSW_9_4_2/src/UserCode/TopAnalysis/prod/ttbar/CreateCrabConfigFilesData.py

Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2018-10-19 11:57:55,126: 	 Executing command: 'submit'
DEBUG 2018-10-19 11:57:55,127: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2018-10-19 11:57:55,139: 	 Checking credentials
DEBUG 2018-10-19 11:57:55,140: 	 Found proxy file /tmp/x509up_u107749
DEBUG 2018-10-19 11:57:55,140: 	 Getting proxy life time left
DEBUG 2018-10-19 11:57:56,582: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -timeleft
 output : 602885

 error: 
 retcode : 0
DEBUG 2018-10-19 11:57:58,031: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -actimeleft
 output : 602884

 error: 
 retcode : 0
DEBUG 2018-10-19 11:57:58,031: 	 Proxy valid for 167:28:05 hours
INFO 2018-10-19 11:57:58,035: 	 Will use CRAB configuration file CreateCrabConfigFilesData.py
DEBUG 2018-10-19 11:57:58,035: 	 Loading CRAB configuration file.
ERROR 2018-10-19 11:57:58,193: 	 Error while loading CRAB configuration:
Unable to find a Configuration object instance in file:
/afs/cern.ch/user/g/gbakas/CRAB3-jobs/CMSSW_9_4_2/src/UserCode/TopAnalysis/prod/ttbar/CreateCrabConfigFilesData.py

Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2018-10-19 11:57:58,193: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 303, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 84, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
Unable to find a Configuration object instance in file:
/afs/cern.ch/user/g/gbakas/CRAB3-jobs/CMSSW_9_4_2/src/UserCode/TopAnalysis/prod/ttbar/CreateCrabConfigFilesData.py

Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2018-10-19 11:59:16,729: 	 Executing command: 'submit'
DEBUG 2018-10-19 11:59:16,729: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2018-10-19 12:03:11,526: 	 Executing command: 'submit'
DEBUG 2018-10-19 12:03:11,528: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2018-10-19 12:03:11,544: 	 Checking credentials
DEBUG 2018-10-19 12:03:11,546: 	 Found proxy file /tmp/x509up_u107749
DEBUG 2018-10-19 12:03:11,546: 	 Getting proxy life time left
DEBUG 2018-10-19 12:03:12,979: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -timeleft
 output : 602569

 error: 
 retcode : 0
ERROR 2018-10-19 12:03:13,052: 	 Keyboard Interrupted
DEBUG 2018-10-19 12:23:55,211: 	 Executing command: 'kill'
DEBUG 2018-10-19 12:23:55,212: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
ERROR 2018-10-19 12:23:55,212: 	 Error: 181019_102213:gbakas_crab_JetHT_Run2016C-03Feb2017-v1 is not a valid CRAB project directory.
ERROR 2018-10-19 12:23:55,212: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/kill.py", line 55, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 575, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: 181019_102213:gbakas_crab_JetHT_Run2016C-03Feb2017-v1 is not a valid CRAB project directory.
DEBUG 2018-10-19 12:25:05,964: 	 Executing command: 'kill'
DEBUG 2018-10-19 12:25:05,966: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
ERROR 2018-10-19 12:25:05,967: 	 Error: Please indicate the CRAB project directory with --dir=<project-directory>.
ERROR 2018-10-19 12:25:05,967: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/kill.py", line 55, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 571, in validateOptions
    raise ex
MissingOptionException: [91mError[0m: Please indicate the CRAB project directory with --dir=<project-directory>.
DEBUG 2018-10-19 12:25:18,393: 	 Executing command: 'kill'
DEBUG 2018-10-19 12:25:18,393: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
ERROR 2018-10-19 12:25:18,394: 	 Error: 181019_102213:gbakas_crab_JetHT_Run2016C-03Feb2017-v1 is not a valid CRAB project directory.
ERROR 2018-10-19 12:25:18,394: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/kill.py", line 55, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 575, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: 181019_102213:gbakas_crab_JetHT_Run2016C-03Feb2017-v1 is not a valid CRAB project directory.
DEBUG 2018-10-19 12:25:40,082: 	 Executing command: 'kill'
DEBUG 2018-10-19 12:25:40,082: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
ERROR 2018-10-19 12:25:40,082: 	 Error: gbakas_crab_JetHT_Run2016C-03Feb2017-v1 is not a valid CRAB project directory.
ERROR 2018-10-19 12:25:40,082: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/kill.py", line 55, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 575, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: gbakas_crab_JetHT_Run2016C-03Feb2017-v1 is not a valid CRAB project directory.
DEBUG 2018-10-19 12:25:45,415: 	 Executing command: 'kill'
DEBUG 2018-10-19 12:25:45,415: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
ERROR 2018-10-19 12:25:45,416: 	 Error: gbakas_crab_JetHT_Run2016C-03Feb2017-v1 is not a valid CRAB project directory.
ERROR 2018-10-19 12:25:45,416: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/kill.py", line 55, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 575, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: gbakas_crab_JetHT_Run2016C-03Feb2017-v1 is not a valid CRAB project directory.
DEBUG 2018-10-19 12:26:09,044: 	 Executing command: 'kill'
DEBUG 2018-10-19 12:26:09,044: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
ERROR 2018-10-19 12:26:09,044: 	 Error: ir= is not a valid CRAB project directory.
ERROR 2018-10-19 12:26:09,045: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/kill.py", line 55, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 575, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: ir= is not a valid CRAB project directory.
DEBUG 2018-10-19 12:26:17,189: 	 Executing command: 'kill'
DEBUG 2018-10-19 12:26:17,189: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
ERROR 2018-10-19 12:26:17,190: 	 Error: 181019_102213:gbakas_crab_JetHT_Run2016C-03Feb2017-v1 is not a valid CRAB project directory.
ERROR 2018-10-19 12:26:17,190: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/kill.py", line 55, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 575, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: 181019_102213:gbakas_crab_JetHT_Run2016C-03Feb2017-v1 is not a valid CRAB project directory.
DEBUG 2018-10-19 12:26:50,863: 	 Executing command: 'kill'
DEBUG 2018-10-19 12:26:50,864: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
ERROR 2018-10-19 12:26:50,864: 	 Error: 181019_102213 is not a valid CRAB project directory.
ERROR 2018-10-19 12:26:50,864: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/kill.py", line 55, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 575, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: 181019_102213 is not a valid CRAB project directory.
DEBUG 2018-10-19 12:26:54,471: 	 Executing command: 'kill'
DEBUG 2018-10-19 12:26:54,471: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
ERROR 2018-10-19 12:26:54,471: 	 Error: 181019_102213: is not a valid CRAB project directory.
ERROR 2018-10-19 12:26:54,471: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/kill.py", line 55, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 575, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: 181019_102213: is not a valid CRAB project directory.
DEBUG 2018-10-19 12:47:12,187: 	 Executing command: 'status'
DEBUG 2018-10-19 12:47:12,190: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2018-10-19 14:10:26,009: 	 Executing command: 'submit'
DEBUG 2018-10-19 14:10:26,011: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2018-10-19 14:10:26,020: 	 Checking credentials
DEBUG 2018-10-19 14:10:26,021: 	 Found proxy file /tmp/x509up_u107749
DEBUG 2018-10-19 14:10:26,022: 	 Getting proxy life time left
DEBUG 2018-10-19 14:10:27,433: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -timeleft
 output : 594934

 error: 
 retcode : 0
DEBUG 2018-10-19 14:10:28,963: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -actimeleft
 output : 594933

 error: 
 retcode : 0
DEBUG 2018-10-19 14:10:28,963: 	 Proxy valid for 165:15:34 hours
INFO 2018-10-19 14:10:28,964: 	 Will use CRAB configuration file crab_JetHT_Run2016B-03Feb2017_ver1-v1.py
DEBUG 2018-10-19 14:10:28,964: 	 Loading CRAB configuration file.
DEBUG 2018-10-19 14:10:28,979: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2018-10-19 14:10:28,980: 	 Working area '/afs/cern.ch/user/g/gbakas/CRAB3-jobs/CMSSW_9_4_2/src/UserCode/TopAnalysis/prod/ttbar/crab_JetHT_Run2016B-03Feb2017_ver1-v1' already exists 
Please change the requestName in the config file
ERROR 2018-10-19 14:10:28,980: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 307, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/g/gbakas/CRAB3-jobs/CMSSW_9_4_2/src/UserCode/TopAnalysis/prod/ttbar/crab_JetHT_Run2016B-03Feb2017_ver1-v1' already exists 
Please change the requestName in the config file
DEBUG 2018-10-19 14:22:24,595: 	 Executing command: 'status'
DEBUG 2018-10-19 14:22:24,596: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
ERROR 2018-10-19 14:22:24,596: 	 Error: = is not a valid CRAB project directory.
ERROR 2018-10-19 14:22:24,596: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1021, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 575, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: = is not a valid CRAB project directory.
DEBUG 2018-10-19 14:22:34,072: 	 Executing command: 'status'
DEBUG 2018-10-19 14:22:34,072: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
ERROR 2018-10-19 14:22:34,465: 	 Error: = is not a valid CRAB project directory.
ERROR 2018-10-19 14:22:34,466: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1021, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 575, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: = is not a valid CRAB project directory.
DEBUG 2018-10-19 14:23:16,561: 	 Executing command: 'status'
DEBUG 2018-10-19 14:23:16,563: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
ERROR 2018-10-19 14:23:16,566: 	 Error: = is not a valid CRAB project directory.
ERROR 2018-10-19 14:23:16,566: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1021, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 575, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: = is not a valid CRAB project directory.
DEBUG 2018-10-19 14:29:40,436: 	 Executing command: 'submit'
DEBUG 2018-10-19 14:29:40,437: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2018-10-19 14:29:40,444: 	 Checking credentials
DEBUG 2018-10-19 14:29:40,444: 	 Found proxy file /tmp/x509up_u107749
DEBUG 2018-10-19 14:29:40,445: 	 Getting proxy life time left
DEBUG 2018-10-19 14:29:41,469: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -timeleft
 output : 593780

 error: 
 retcode : 0
DEBUG 2018-10-19 14:29:42,381: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -actimeleft
 output : 593779

 error: 
 retcode : 0
DEBUG 2018-10-19 14:29:42,381: 	 Proxy valid for 164:56:20 hours
ERROR 2018-10-19 14:29:42,382: 	 CRAB configuration file crabConfig.py not found.
ERROR 2018-10-19 14:29:42,382: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 303, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 46, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crabConfig.py not found.
DEBUG 2018-10-19 14:29:42,790: 	 Executing command: 'submit'
DEBUG 2018-10-19 14:29:42,790: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2018-10-19 14:29:42,798: 	 Checking credentials
DEBUG 2018-10-19 14:29:42,798: 	 Found proxy file /tmp/x509up_u107749
DEBUG 2018-10-19 14:29:42,798: 	 Getting proxy life time left
DEBUG 2018-10-19 14:29:43,718: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -timeleft
 output : 593778

 error: 
 retcode : 0
DEBUG 2018-10-19 14:29:44,829: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -actimeleft
 output : 593777

 error: 
 retcode : 0
DEBUG 2018-10-19 14:29:44,830: 	 Proxy valid for 164:56:18 hours
ERROR 2018-10-19 14:29:44,830: 	 CRAB configuration file crabConfig.py not found.
ERROR 2018-10-19 14:29:44,830: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 303, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 46, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crabConfig.py not found.
DEBUG 2018-10-19 14:29:45,224: 	 Executing command: 'submit'
DEBUG 2018-10-19 14:29:45,224: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2018-10-19 14:29:45,233: 	 Checking credentials
DEBUG 2018-10-19 14:29:45,233: 	 Found proxy file /tmp/x509up_u107749
DEBUG 2018-10-19 14:29:45,233: 	 Getting proxy life time left
DEBUG 2018-10-19 14:29:46,464: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -timeleft
 output : 593775

 error: 
 retcode : 0
DEBUG 2018-10-19 14:29:47,691: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -actimeleft
 output : 593774

 error: 
 retcode : 0
DEBUG 2018-10-19 14:29:47,691: 	 Proxy valid for 164:56:15 hours
ERROR 2018-10-19 14:29:47,691: 	 CRAB configuration file crabConfig.py not found.
ERROR 2018-10-19 14:29:47,692: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 303, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 46, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crabConfig.py not found.
DEBUG 2018-10-19 14:29:48,113: 	 Executing command: 'submit'
DEBUG 2018-10-19 14:29:48,113: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2018-10-19 14:29:48,120: 	 Checking credentials
DEBUG 2018-10-19 14:29:48,120: 	 Found proxy file /tmp/x509up_u107749
DEBUG 2018-10-19 14:29:48,120: 	 Getting proxy life time left
DEBUG 2018-10-19 14:29:48,938: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -timeleft
 output : 593773

 error: 
 retcode : 0
DEBUG 2018-10-19 14:29:49,751: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -actimeleft
 output : 593772

 error: 
 retcode : 0
DEBUG 2018-10-19 14:29:49,751: 	 Proxy valid for 164:56:13 hours
ERROR 2018-10-19 14:29:49,751: 	 CRAB configuration file crabConfig.py not found.
ERROR 2018-10-19 14:29:49,752: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 303, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 46, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crabConfig.py not found.
DEBUG 2018-10-19 14:29:50,161: 	 Executing command: 'submit'
DEBUG 2018-10-19 14:29:50,161: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2018-10-19 14:29:50,168: 	 Checking credentials
DEBUG 2018-10-19 14:29:50,168: 	 Found proxy file /tmp/x509up_u107749
DEBUG 2018-10-19 14:29:50,168: 	 Getting proxy life time left
DEBUG 2018-10-19 14:29:51,084: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -timeleft
 output : 593770

 error: 
 retcode : 0
DEBUG 2018-10-19 14:29:52,004: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -actimeleft
 output : 593770

 error: 
 retcode : 0
DEBUG 2018-10-19 14:29:52,004: 	 Proxy valid for 164:56:10 hours
ERROR 2018-10-19 14:29:52,004: 	 CRAB configuration file crabConfig.py not found.
ERROR 2018-10-19 14:29:52,005: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 303, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 46, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crabConfig.py not found.
DEBUG 2018-10-19 14:29:52,609: 	 Executing command: 'submit'
DEBUG 2018-10-19 14:29:52,609: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2018-10-19 14:29:52,617: 	 Checking credentials
DEBUG 2018-10-19 14:29:52,619: 	 Found proxy file /tmp/x509up_u107749
DEBUG 2018-10-19 14:29:52,619: 	 Getting proxy life time left
ERROR 2018-10-19 14:29:53,611: 	 Keyboard Interrupted
